import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { StyledEngineProvider } from '@mui/material/styles';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import React from 'react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <React.StrictMode>
      <StyledEngineProvider injectFirst>
        <html lang="en">

          <AppRouterCacheProvider>
            <body id="#root" className={inter.className}>{children}</body>
          </AppRouterCacheProvider>
        </html>
      </StyledEngineProvider>
    </React.StrictMode>
  )
}
