name: Run navy yard scraper
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 5'
jobs:
  scrape-navy-yard:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    environment: scrape-env
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Install dependencies (shared)
        run: npm ci
        working-directory: shared

      - name: Install Playwright
        run: npx playwright install --with-deps chromium
        working-directory: shared

      - name: Install dependencies (navy-yard)
        run: npm ci
        working-directory: navy-yard

      - name: Run navy-yard scraper
        run: npm run navy-yard
        working-directory: navy-yard
        env:
          NAVY_YARD_PASSWORD: ${{ secrets.NAVY_YARD_PASSWORD }}
          NAVY_YARD_EMAIL: ${{ secrets.NAVY_YARD_EMAIL }}
          NODE_ENV: production
